import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import json from '@eslint/json';
import markdown from '@eslint/markdown';
import { defineConfig } from 'eslint/config';
import publicMethods from './config/plugins/publicMethods';

export default defineConfig([
	{
		files: ['**/*.{js,mjs,cjs,ts,mts,cts}'],
		plugins: { js },
		extends: ['js/recommended'],
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
	},
	tseslint.configs.recommended,
	{
		files: ['**/*.json'],
		plugins: { json },
		language: 'json/json',
		extends: ['json/recommended'],
	},
	{
		files: ['**/*.md'],
		plugins: { markdown },
		language: 'markdown/gfm',
		extends: ['markdown/recommended'],
	},
	{
		rules: {
			'array-callback-return': ['error', { allowImplicit: true, checkForEach: true }],
			'block-scoped-var': 'error',
			'complexity': ['warn', { max: 10, variant: 'modified' }],
			'consistent-return': 'error',
			'curly': ['error', 'multi-line'],
			'default-param-last': 'error',
			'dot-notation': ['error', { allowKeywords: true }],
			'dot-location': ['error', 'property'],
			'eqeqeq': ['error', 'always', { null: 'ignore' }],
			'grouped-accessor-pairs': 'error',
			'guard-for-in': 'error',
			'max-classes-per-file': ['error', 1],
			'no-case-declarations': 'error',
			'no-constructor-return': 'error',
			'no-else-return': ['error', { allowElseIf: false }],
			'no-empty-function': [
				'error',
				{
					allow: ['arrowFunctions', 'functions', 'methods'],
				},
			],
			'no-empty-pattern': 'error',
			'no-empty-static-block': 'error',
			'no-eq-null': 'error',
			'no-eval': 'error',
			'no-extend-native': 'error',
			'no-extra-bind': 'error',
			'no-extra-label': 'error',
			'no-fallthrough': 'warn',
			'no-floating-decimal': 'error',
			'no-global-assign': ['error', { exceptions: [] }],
			'no-implicit-coercion': 'error',
			'no-implicit-globals': 'error',
			'no-implied-eval': 'error',
			'no-invalid-this': 'error',
			'no-iterator': 'error',
			'no-labels': 'error',
			'no-lone-blocks': 'error',
			'no-loop-func': 'error',
			'no-multi-spaces': 'error',
			'no-multi-str': 'error',
			'no-new': 'error',
			'no-new-func': 'error',
			'no-new-wrappers': 'error',
			'no-nonoctal-decimal-escape': 'error',
			'no-object-constructor': 'off',
			'no-octal': 'error',
			'no-octal-escape': 'error',
			'no-param-reassign': [
				'error',
				{
					props: true,
					ignorePropertyModificationsFor: [
						'acc', // for reduce accumulators
						'accumulator', // for reduce accumulators
					],
				},
			],
			'no-proto': 'error',
			'no-redeclare': 'error',
			'no-return-assign': ['error', 'always'],
			'no-return-await': 'error',
			'no-script-url': 'error',
			'no-self-assign': ['error', { props: true }],
			'no-self-compare': 'error',
			'no-sequences': 'error',
			'no-throw-literal': 'error',
			'no-unused-expressions': [
				'error',
				{
					allowShortCircuit: false,
					allowTernary: false,
					allowTaggedTemplates: false,
				},
			],
			'no-unused-labels': 'error',
			'no-useless-call': 'off',
			'no-useless-catch': 'error',
			'no-useless-concat': 'error',
			'no-useless-escape': 'error',
			'no-useless-return': 'error',
			'no-void': 'error',
			'no-with': 'error',
			'prefer-promise-reject-errors': 'off',
			'prefer-named-capture-group': 'off',
			'prefer-object-has-own': 'error',
			'prefer-regex-literals': [
				'error',
				{
					disallowRedundantWrapping: true,
				},
			],
			'radix': 'error',
			'require-await': 'off',
			'require-unicode-regexp': 'off',
			'vars-on-top': 'error',
			'wrap-iife': ['error', 'outside', { functionPrototypeMethods: false }],
			'yoda': 'error',
			'for-direction': 'error',
			'getter-return': ['error', { allowImplicit: true }],
			'no-async-promise-executor': 'error',
			'no-await-in-loop': 'error',
			'no-compare-neg-zero': 'error',
			'no-cond-assign': ['error', 'always'],
			'no-console': 'off',
			'no-constant-binary-expression': 'error',
			'no-constant-condition': 'warn',
			'no-control-regex': 'error',
			'no-debugger': 'error',
			'no-dupe-args': 'error',
			'no-dupe-else-if': 'error',
			'no-dupe-keys': 'error',
			'no-duplicate-case': 'error',
			'no-empty': 'error',
			'no-ex-assign': 'off',
			'no-extra-boolean-cast': 'error',
			'no-extra-parens': [
				'off',
				'all',
				{
					conditionalAssign: true,
					nestedBinaryExpressions: false,
					returnAssign: false,
					enforceForArrowConditionals: false,
				},
			],
			'no-extra-semi': 'error',
			'no-func-assign': 'error',
			'no-import-assign': 'error',
			'no-inner-declarations': 'error',
			'no-invalid-regexp': 'error',
			'no-irregular-whitespace': 'error',
			'no-loss-of-precision': 'error',
			'no-misleading-character-class': 'error',
			'no-obj-calls': 'error',
			'no-new-native-nonconstructor': 'error',
			'no-promise-executor-return': 'error', // ?
			'no-prototype-builtins': 'error',
			'no-regex-spaces': 'error',
			'no-setter-return': 'error',
			'no-sparse-arrays': 'error',
			'no-template-curly-in-string': 'error',
			'no-unexpected-multiline': 'error',
			'no-unreachable': 'error',
			'no-unreachable-loop': 'error',
			'no-unsafe-finally': 'error',
			'no-unsafe-negation': 'error',
			'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
			'no-unused-private-class-members': 'off',
			'no-useless-backreference': 'error',
			'use-isnan': 'error',
			'valid-typeof': ['error', { requireStringLiterals: true }],
			'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
			'global-require': 'off',
			'no-plusplus': 'off',
			'prefer-arrow-callback': 'off',
			'no-unused-vars': 'off',
			'@typescript-eslint/no-unused-vars': [
				'error',
				{
					varsIgnorePattern: '^_',
					argsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
					destructuredArrayIgnorePattern: '^_',
				},
			],
		},
	},
	{
		plugins: {
			publicMethods,
		},
		rules: {
			'publicMethods/public-class-methods-use-this': 'error',
		},
	},
]);
